# Tracing
tracing:
  jaeger:
    enabled: \${JAEGER_ENABLE:\`true\`}
    sender:
      agentHost: \${JAEGER_AGENT_HOST:\`localhost\`}
      agentPort: \${JAEGER_AGENT_PORT:\`6831\`}

    sampler:
      managerHostPort: \${JAEGER_SAMPLING_MANAGER:\`localhost:5778\`}